theme: eternity

title: Malith Kaveesha

params:
  homePage: "/work"

taxonomies:
  tag: tags


menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: people
      url: /tags/first-tag/
      weight: 2